apiVersion: v1
kind: Service
metadata:
  name: book-app-service-1
  labels:
    app: book-app
spec:
  type: NodePort
  selector:
    app: book-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8081
      nodePort: 30080
